# Generated by Django 4.2.5 on 2023-09-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_database', '0003_alter_active_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_profile',
            name='image',
            field=models.ImageField(default='profile_default_icon.png', upload_to='profil_pic'),
        ),
        migrations.AlterField(
            model_name='trash_profile',
            name='image',
            field=models.ImageField(default='profile_default_icon.png', upload_to='profil_pic'),
        ),
    ]
