# Generated by Django 4.2.5 on 2023-09-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_database', '0004_alter_active_profile_image_alter_trash_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash_profile',
            name='image',
        ),
    ]
